### ISSUE TITLE
HR should be able to view department details

### ISSUE THREAD

**Issue by copypastedeveloper** [Order-of-the-Public-Void/Workforce-Management#7]
**Given** user is viewing list of departments
**When** user clicks on a department
**Then** a view should be presented with the department name as a header
**And** a list of employees currently assigned to that department should be listed

**Comment by aefinch** [comment]
Can you show the list of employees in the detail view?  I don't see any showing up. @webbdm

**Comment by webbdm** [comment]
They should be there now in my PR

**Comment by aefinch** [comment]
👻
